eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance: 
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id}:${random.value}

server:
  port: ${PORT:${SERVER_PORT:0}}

words: NA

---
spring:
  config:
    activate:
      on-profile: subject
  application:
    name: lab-4-subject
words: I,You,He,She,It

---
spring:
  config:
    activate:
      on-profile: verb
  application:
    name: lab-4-verb
words: ran,knew,had,saw,bought

---
spring:
  config:
    activate:
      on-profile: article
  application:
    name: lab-4-article
words: a,the

---
spring:
  config:
    activate:
      on-profile: adjective
  application:
    name: lab-4-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  config:
    activate:
      on-profile: noun
  application:
    name: lab-4-noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
spring:
  config:
    activate:
      on-profile: sentence
  application:
    name: lab-4-sentence
words: NotApplicable
server:
  port: 8020

---
spring:
  config:
    activate:
      on-profile: clod-noun
  application:
    name: noun
words: icicle,refrigerator,blizzard,snowball
